# Generated by Django 6.0.5 on 2026-05-13 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especializacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=150)),
                ('responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sala', to='app_gestion_actividades.responsablesala')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('horario', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('plazas_disponibles', models.IntegerField()),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='app_gestion_actividades.monitor')),
                ('sala_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_principales', to='app_gestion_actividades.sala')),
                ('salas_secundarias', models.ManyToManyField(blank=True, related_name='actividades_secundarias', to='app_gestion_actividades.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('asistencia', models.BooleanField(default=False)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_actividades.actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_actividades.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'actividad')},
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='usuarios',
            field=models.ManyToManyField(related_name='actividades', through='app_gestion_actividades.Inscripcion', to='app_gestion_actividades.usuario'),
        ),
    ]
